// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBO33gVEm5CiDt5WW1zdBjO3_SaMzIJGk8',
    appId: '1:552937312893:web:5ec02ff56c424035701714',
    messagingSenderId: '552937312893',
    projectId: 'chatte-app-4f56a',
    authDomain: 'chatte-app-4f56a.firebaseapp.com',
    storageBucket: 'chatte-app-4f56a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAubz6-KfGCN33QCn2YwsN69dbF2f7lV9E',
    appId: '1:552937312893:android:44ed21f220d42583701714',
    messagingSenderId: '552937312893',
    projectId: 'chatte-app-4f56a',
    storageBucket: 'chatte-app-4f56a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByOgSm7aBne1_M6cI_I9p1s1Eu_8UFtLg',
    appId: '1:552937312893:ios:e6c8c94f5a123830701714',
    messagingSenderId: '552937312893',
    projectId: 'chatte-app-4f56a',
    storageBucket: 'chatte-app-4f56a.firebasestorage.app',
    iosBundleId: 'com.example.chatterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByOgSm7aBne1_M6cI_I9p1s1Eu_8UFtLg',
    appId: '1:552937312893:ios:e6c8c94f5a123830701714',
    messagingSenderId: '552937312893',
    projectId: 'chatte-app-4f56a',
    storageBucket: 'chatte-app-4f56a.firebasestorage.app',
    iosBundleId: 'com.example.chatterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBO33gVEm5CiDt5WW1zdBjO3_SaMzIJGk8',
    appId: '1:552937312893:web:c0e034736419cc3a701714',
    messagingSenderId: '552937312893',
    projectId: 'chatte-app-4f56a',
    authDomain: 'chatte-app-4f56a.firebaseapp.com',
    storageBucket: 'chatte-app-4f56a.firebasestorage.app',
  );
}
